### ISSUE TITLE
Device Deployment

### ISSUE THREAD

**Issue by Orgbrat** [damienaicheh/MicrosoftAuthenticationProject#1]
Very good article and it helped me a lot. I have created an application that uses this process to sign-in to OneDrive and sync the Xamarin mobile application data file. Everything works fine in UWP, Android and iOS (simulator) but the app will not deploy to a iOS physical device. I have created an ad-hoc distribution provision profile and tried that thru Microsoft App Center. Application still will not deploy to physical device. Is there something that needs to be checked in the provisioning profile on Apple developer site for the iOS keychain access that might stop the deployment?

Steve

**Comment by damienaicheh** [comment]
Hi, thanks, I have no idea, it should be working. Try deploy your application without the Microsoft Authentication if it's easy to disable, to be sure that the problem comes from here. Did you check that your device is on the list of devices associated to your Apple dev account to be authorised to deploy on it ? You can check that directly on the Apple website
